### ISSUE TITLE
gene_use Error 

### ISSUE THREAD

**Issue by mkorshe** [quadbiolab/VoxHunt#2]
hey! 

I have a problem with command # Find 300 most variable genes from the E13.5 mouse brain

` genes_use <- variable_genes('E13', 300)$gene`

Error in `[[.H5File`(self, paste0(attribute.layer, "/", col.names)) : 
  An object with name col_attrs/cell_names does not exist in this group

**Comment by joschif** [comment]
Hi mkorshe, 

I am very sorry for the issues you are experiencing! Could provide me with the output of `sessionInfo()`, so I can try to replicate the error? 

Best,
Jonas

**Comment by joschif** [comment]
Since both of you problems were related to hdf5r/loomR, I just pushed a new version which removes these as dependencies and uses .rds files instead. I hope this fixes your issues. If you want to try it, you can download the new .rds data from [here](http://dx.doi.org/10.17632/g4xg38mwcn.1) and reinstall voxhunt from github.

**Comment by mkorshe** [comment]
Hi! 

I see you replaced .loom objects to .Rsd and it helped. 

The first few times when I was trying to run it, my R session was aborted (from RStudio and from a terminal). 
But now everything works!

Thank you!

**Comment by joschif** [comment]
Happy to help, thanks for reporting the issues!
